services:
  - type: web
    name: netflix-nftoken-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gato.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8945828877:AAFNznpCroIeQblmaw7HVSqjFOlDB2e8Ugs
      - key: WEBHOOK_URL
        value: https://tunombre.onrender.com
      - key: PORT
        value: 8080
      - key: TZ
        value: America/Santiago
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
