# render.yaml
services:
  - type: worker
    name: netflix-nftoken-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8945828877:AAFNznpCroIeQblmaw7HVSqjFOlDB2e8Ugs
      - key: TZ
        value: America/Santiago
